{% set name = "LabelImg" %}
{% set version = "1.8.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/labelImg-{{ version }}.tar.gz
  sha256: dd72a80084fa9264b4ebf9734734ea6259ed603172adc468933d20052fea8430

build:
  number: 4
  entry_points:
    - labelImg=labelImg.labelImg:main
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen
  noarch: python
  string: "linux_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [linux]
  string: "osx_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"   # [osx]

requirements:
  host:
    - pip
    - py2app  # [osx]
    - python {{ python_min }}
  run:
    - lxml
    - pyqt
    - python >={{ python_min }}
    - __unix
    - __linux  # [linux]
    - __osx  # [osx]

test:
  imports:
    - labelImg
    - libs
  commands:
    - pip check
    - labelImg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tzutalin/labelImg
  summary: LabelImg is a graphical image annotation tool and label object bounding boxes in images
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
